[package]
name = "liquidity-pool-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false
[dependencies.liquidity-pool]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.0"
