[package]
name = "lending-pool-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.lending-pool]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-debug]
version = "0.29.3"
