[package]
name = "common-tokens"
version = "0.0.0"
authors = ["CostinCarabas <costin.carabas@multiversx.com>"]
edition = "2018"

[lib]
path = "src/tokens.rs"
[dependencies.multiversx-sc]
version = "0.41.0"
