[package]
name = "aggregator-mock"
version = "0.0.0"
authors = ["CostinCarabas <costin.carabas@multiversx.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
[dependencies.multiversx-sc]
version = "0.41.0"
[dev-dependencies.multiversx-sc-scenario]
version = "0.41.0"
